services:
  - type: web
    name: catalog-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn catalog_service.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: catalog_service.settings
      - key: PYTHON_VERSION
        value: 3.11
